### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by canon0826** [canon0826/furima-39903#21]
# URL
https://furima-39903.onrender.com

# 出品者用のメールアドレスとパスワード
   test@1
   ts1234

# 購入者用のメールアドレスとパスワード
   test@2
   ts4321

**Comment by snkw-works** [comment]
@canon0826 さん、ご提出ありがとうございます‼︎

Basic認証のIDとパスワードの記載がなかったため、動作確認ができておりません。
issueにBasic認証のIDとパスワードを記載の上、再度ご提出いただきますようお願いいたします。

修正が完了しましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by canon0826** [comment]
申し訳ございません。Basic認証のIDとパスワードです。
宜しくお願い致します。

 ID   furima
パスワード　1234

**Comment by snkw-works** [comment]
@canon0826 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう（--- は初期値として設定すること）**
「新品・未使用」が正しく表示されていない状態です。
![スクリーンショット_2024-02-18_12_52_50](https://github.com/canon0826/furima-39903/assets/54050089/a0a77a8b-7ce3-4ada-960b-c95be0e0aa36)

#### 商品削除機能
- [ ] **削除が完了したら、トップページに遷移するよう修正しましょう**
削除ボタンをクリックした後、詳細ページに留まってしまいます。

#### 商品購入機能
- [ ] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
現在、クレジットカードの情報入力欄は表示されていますが、カーソルを合わせても入力ができない状態です。

- [ ] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であるよう修正しましょう**
「都道府県」が空欄にも関わらず、エラーメッセージが表示されない状態です。

※購入機能と購入後に関する項目に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by canon0826** [comment]
修正確認お願い致します。

**Comment by motomuun** [comment]
@canon0826 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [ ] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
自身が出品していない売却済みの商品情報編集ページへ遷移しようとすると、エラーページに遷移します。トップページに遷移するように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by canon0826** [comment]
修正確認お願い致します。

**Comment by motomuun** [comment]
@canon0826 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
